workflows:
  expo_android:
    name: Expo Android Build
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - name: Install deps
        script: npm install
      - name: Build Android (EAS)
        script: |
          npm install -g eas-cli
          eas build -p android --profile production --non-interactive
